# Generated by Django 5.2.7 on 2025-10-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_offcampus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='off_campuses',
            field=models.ManyToManyField(blank=True, null=True, related_name='staff_users', to='accounts.offcampus'),
        ),
    ]
