# Generated by Django 5.2.7 on 2025-10-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_off_campuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='off_campuses',
            field=models.ManyToManyField(blank=True, related_name='staff_users', to='accounts.offcampus'),
        ),
    ]
